# Generated by Django 4.2 on 2023-06-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alert", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="recipients",
        ),
        migrations.AddField(
            model_name="alert",
            name="date",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="tags",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="title",
            field=models.CharField(default="Denúncia genérica", max_length=30),
        ),
    ]
