# Generated by Django 4.2 on 2023-10-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(choices=[('M', 'Manhã'), ('E', 'Tarde'), ('N', 'Noite')], default='M', max_length=1),
        ),
    ]
