# Generated by Django 4.2 on 2023-11-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_course_time'),
        ('management', '0003_alter_programming_classroom_and_more'),
    ]

    operations = [
    ]
