# Generated by Django 4.2 on 2023-11-17 02:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0004_merge_20231110_1403"),
        ("management", "0004_merge_20231113_2008"),
    ]

    operations = []
