# Generated by Django 4.2 on 2025-03-16 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0005_merge_20231116_2334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classrooms",
                to="management.course",
            ),
        ),
    ]
