version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - static:/app/static
    command: python manage.py runserver 0.0.0.0:8080
    env_file:
      - .env
    environment:
      - DEBUG=1
    depends_on:
      - node

  node:
    image: node:20
    user: node
    working_dir: /app
    volumes:
      - .:/app
      - static:/app/static
    command: npm run watch

  web:
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:8000 gunicorn.wsgi --workers=4
    volumes:
      - static:/app/static # Static volume shared with both app and web services
      - media:/app/media # Media volume shared with web service
    expose:
      - "8000"
    networks:
      - django-network

  nginx:
    build: nginx
    restart: always
    volumes:
      - static:/app/static # Static volume shared with both web and nginx services
      - media:/app/media # Media volume shared with web service
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - django-network

networks:
  django-network:
    name: django-network

volumes:
  media:
  static:
