# Generated by Django 4.2 on 2023-09-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="phone",
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
