# Generated by Django 4.2 on 2023-10-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="division",
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
    ]
