# Generated by Django 4.2 on 2023-08-29 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_group", models.PositiveSmallIntegerField(null=True)),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MON", "Segunda"),
                            ("TUE", "Terça"),
                            ("WED", "Quarta"),
                            ("THU", "Quinta"),
                            ("SUN", "Sexta"),
                        ],
                        default="MON",
                        max_length=15,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "classroom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.classroom",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "classe",
                "verbose_name_plural": "classes",
            },
        ),
        migrations.DeleteModel(
            name="Class",
        ),
    ]
