# Generated by Django 4.2 on 2023-05-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="distance",
            field=models.FloatField(default=0, null=True),
        ),
    ]
