# Generated by Django 4.2 on 2023-05-08 22:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Obrigatório. 100 ou menos. Apenas letras e ponto",
                max_length=100,
                unique=True,
                validators=[core.models.NameValidator()],
            ),
        ),
    ]
