# Generated by Django 4.2 on 2023-06-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_member_distance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="public_schooling",
            field=models.CharField(
                choices=[
                    ("C", "Completo"),
                    ("N", "Nenhuma"),
                    ("E", "Ensino Primário"),
                    ("M", "Ensino Fundamental"),
                    ("H", "Ensino Médio"),
                ],
                default="M",
                max_length=1,
            ),
        ),
    ]
