# Generated by Django 4.2 on 2023-08-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_programming_delete_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programming",
            name="day",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Segunda"),
                    (1, "Terça"),
                    (2, "Quarta"),
                    (3, "Quinta"),
                    (4, "Sexta"),
                ],
                default=0,
            ),
        ),
    ]
