# Generated by Django 4.2 on 2023-05-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_user_name_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cpf",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="rg",
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthdate",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Endereço de email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino"), ("NB", "Não Binário")],
                max_length=2,
                null=True,
            ),
        ),
    ]
