# Generated by Django 4.2 on 2023-09-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_programming_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programming',
            options={'ordering': ['student_group'], 'verbose_name': 'classe', 'verbose_name_plural': 'classes'},
        ),
    ]
