# Generated by Django 4.2 on 2023-05-14 03:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_user_cpf_user_rg_alter_user_birthdate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="cpf",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="rg",
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(default="São Caetano do Sul", max_length=60),
        ),
        migrations.AddField(
            model_name="user",
            name="civil_state",
            field=models.CharField(
                choices=[
                    ("S", "Solteiro"),
                    ("M", "Casado"),
                    ("D", "Divorciado"),
                    ("W", "Viúvo"),
                ],
                default="S",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="complement",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="country_of_origin",
            field=models.CharField(default="Brasil", max_length=40),
        ),
        migrations.AddField(
            model_name="user",
            name="nationality",
            field=models.CharField(default="Brasil", max_length=40),
        ),
        migrations.AddField(
            model_name="user",
            name="natural_city",
            field=models.CharField(default="São Caetano do Sul", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="natural_state",
            field=models.CharField(
                choices=[
                    ("RO", "Ro"),
                    ("AC", "Ac"),
                    ("AM", "Am"),
                    ("RR", "Rr"),
                    ("PA", "Pa"),
                    ("AP", "Ap"),
                    ("TO", "To"),
                    ("MA", "Ma"),
                    ("PI", "Pi"),
                    ("CE", "Ce"),
                    ("RN", "Rn"),
                    ("PB", "Pb"),
                    ("PE", "Pe"),
                    ("AL", "Al"),
                    ("SE", "Se"),
                    ("BA", "Ba"),
                    ("MG", "Mg"),
                    ("ES", "Es"),
                    ("RJ", "Rj"),
                    ("SP", "Sp"),
                    ("PR", "Pr"),
                    ("SC", "Sc"),
                    ("RS", "Rs"),
                    ("MS", "Ms"),
                    ("MT", "Mt"),
                    ("GO", "Go"),
                    ("DF", "Df"),
                ],
                default="SP",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="user",
            name="public_schooling",
            field=models.CharField(
                choices=[
                    ("C", "Completo"),
                    ("N", "Nenhuma"),
                    ("E", "Ensino Primário"),
                    ("M", "Ensino Fundamental"),
                    ("H", "Ensino Média"),
                ],
                default="M",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="street",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthdate",
            field=models.DateField(default=datetime.date(2008, 1, 1)),
        ),
        migrations.AlterField(
            model_name="user",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="core.course",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino"), ("NB", "Não Binário")],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.SlugField(
                choices=[
                    ("0", "Aluno"),
                    ("1", "Professor"),
                    ("2", "Funcionário"),
                    ("3", "Administrador"),
                ],
                default="0",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="relatives",
            field=models.ManyToManyField(to="core.relative"),
        ),
    ]
