# Generated by Django 4.2 on 2023-09-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_programming_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programming",
            options={
                "ordering": ["group"],
                "verbose_name": "classe",
                "verbose_name_plural": "classes",
            },
        ),
        migrations.RenameField(
            model_name="programming",
            old_name="student_group",
            new_name="group",
        ),
        migrations.AlterField(
            model_name="member",
            name="contact_email",
            field=models.EmailField(
                default="john.doe@email.com", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="cpf",
            field=models.CharField(default="", max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="rg",
            field=models.CharField(default="", max_length=9, unique=True),
        ),
    ]
