# Generated by Django 4.2 on 2023-05-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_relative_remove_user_cpf_remove_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino"), ("NB", "Não Binário")],
                default="M",
                max_length=2,
            ),
        ),
    ]
