# Generated by Django 4.2 on 2023-05-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="complement",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="neighborhood",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="user",
            name="street",
            field=models.CharField(max_length=40),
        ),
    ]
