# Generated by Django 4.2 on 2023-07-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_member_country_of_origin_and_more'),
        ('core', '0006_subject_description'),
    ]

    operations = [
    ]
