# Generated by Django 4.2 on 2023-05-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_user_complement_alter_user_neighborhood_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="afro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="cep",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="contact_email",
            field=models.EmailField(default="john.doe@email.com", max_length=254),
        ),
        migrations.AddField(
            model_name="user",
            name="cpf",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="distance",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="rg",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="street_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
