# Generated by Django 4.2 on 2023-07-20 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_subject_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="coordinator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="core.member",
            ),
        ),
    ]
