# Generated by Django 4.2 on 2023-07-21 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_course_coordinator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="coordinator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
