# Generated by Django 4.2 on 2023-05-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_user_afro_user_cep_user_contact_email_user_cpf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="indigenous",
            field=models.BooleanField(default=False),
        ),
    ]
