# Generated by Django 4.2 on 2023-08-05 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_member_course_member_deficiencies_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="class",
            name="course",
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="name",
        ),
        migrations.AddField(
            model_name="class",
            name="classroom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.classroom",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="year",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="member",
            name="division",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="time",
            field=models.CharField(
                choices=[
                    ("M", "Manhã"),
                    ("E", "Tarde"),
                    ("N", "Noite"),
                    ("F", "Integral"),
                ],
                default="M",
                max_length=1,
            ),
        ),
    ]
