# Generated by Django 4.2 on 2023-08-06 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_event_remove_class_course_remove_classroom_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Communicate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=80)),
                ("date", models.DateField()),
                ("image", models.ImageField(null=True, upload_to="communicate/covers")),
                ("info", models.TextField()),
                (
                    "classroom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.classroom",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.course",
                    ),
                ),
            ],
        ),
    ]
