# Generated by Django 4.2 on 2023-08-07 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_communicate"),
    ]

    operations = [
        migrations.AddField(
            model_name="communicate",
            name="private",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="communicate",
            name="date",
            field=models.DateField(auto_created=True),
        ),
        migrations.RemoveField(
            model_name="member",
            name="classrooms",
        ),
        migrations.AddField(
            model_name="member",
            name="classrooms",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="core.classroom",
            ),
        ),
    ]
