# Generated by Django 4.2 on 2023-08-07 00:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_communicate_private_alter_communicate_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="classrooms",
            new_name="classroom",
        ),
    ]
