# Generated by Django 4.2 on 2023-08-07 00:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_rename_classrooms_member_classroom"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Communicate",
            new_name="Announcement",
        ),
    ]
