# Generated by Django 4.2 on 2023-08-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_communicate_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
