# Generated by Django 4.2 on 2023-08-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_announcement_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={"ordering": ["-date"]},
        ),
        migrations.RemoveField(
            model_name="member",
            name="country_of_origin",
        ),
        migrations.RemoveField(
            model_name="member",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="member",
            name="natural_city",
        ),
        migrations.RemoveField(
            model_name="member",
            name="natural_state",
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(default="-", max_length=2),
        ),
        migrations.AlterField(
            model_name="member",
            name="cep",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AlterField(
            model_name="member",
            name="cpf",
            field=models.CharField(default="", max_length=11),
        ),
        migrations.AlterField(
            model_name="member",
            name="rg",
            field=models.CharField(default="", max_length=9),
        ),
        migrations.AlterField(
            model_name="relative",
            name="phone",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=60),
        ),
    ]
