# Generated by Django 4.2 on 2023-08-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_announcement_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="course",
            name="info",
            field=models.TextField(null=True),
        ),
    ]
