<<<<<<< HEAD
# Generated by Django 4.2 on 2023-08-21 12:40
=======
# Generated by Django 4.2 on 2023-08-20 15:14
>>>>>>> 5569efaba3a0fdee830068a139d0e19b42443eb9

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('core', '0018_course_duration_course_info'),
=======
    dependencies = [
        ("core", "0018_course_duration_course_info"),
>>>>>>> 5569efaba3a0fdee830068a139d0e19b42443eb9
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='course',
            name='slug',
            field=models.SlugField(default='-', max_length=2, unique=True),
=======
            model_name="course",
            name="slug",
            field=models.SlugField(default="-", max_length=2, unique=True),
>>>>>>> 5569efaba3a0fdee830068a139d0e19b42443eb9
        ),
    ]
