# Generated by Django 4.2 on 2023-08-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_course_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="slug",
        ),
        migrations.AlterField(
            model_name="classroom",
            name="year",
            field=models.IntegerField(default=2023),
        ),
    ]
