# Generated by Django 4.2 on 2023-08-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_remove_classroom_slug_alter_classroom_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="duration",
            field=models.FloatField(default=3),
        ),
    ]
