# Generated by Django 4.2 on 2023-04-17 00:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_alter_class_options_alter_course_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="curriculum",
            new_name="subjects",
        ),
        migrations.AddField(
            model_name="subject",
            name="slug",
            field=models.SlugField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(default="---", max_length=3),
        ),
        migrations.AlterField(
            model_name="user",
            name="relatives",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.SlugField(
                choices=[
                    ("0", "Aluno"),
                    ("1", "Responsável"),
                    ("2", "Professor"),
                    ("3", "Funcionário"),
                ],
                default="0",
                max_length=1,
            ),
        ),
    ]
