# Generated by Django 4.2 on 2023-04-17 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_rename_curriculum_course_subjects_subject_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="day",
            field=models.CharField(
                choices=[
                    ("MON", "Segunda-feira"),
                    ("TUE", "Terça-feira"),
                    ("WED", "Quarta-feira"),
                    ("THU", "Quinta-feira"),
                    ("SUN", "Sexta-feira"),
                ],
                default="MON",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="order",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(default="-", max_length=7),
        ),
        migrations.AlterField(
            model_name="user",
            name="classes",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="api.class",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="relatives",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
