# Generated by Django 4.2 on 2023-04-17 02:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0004_class_day_class_order_alter_course_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="slug",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="user",
            name="relatives",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
