# Generated by Django 4.2 on 2023-04-17 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0005_alter_subject_slug_alter_user_relatives"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="classes",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="api.course",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="relatives",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
