# Generated by Django 4.2 on 2023-11-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grades", "0002_assessment_division"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="kind",
            field=models.CharField(
                choices=[("A", "Atividade"), ("T", "Prova")], default="A", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="mention",
            name="category",
            field=models.CharField(
                choices=[("B", "Bimestre"), ("C", "Conselho"), ("F", "Final")],
                default="B",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="mention",
            name="justification",
            field=models.CharField(default="", max_length=127),
        ),
    ]
