# Generated by Django 4.2 on 2023-11-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grades", "0003_assessment_kind_mention_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="title",
            field=models.CharField(default="Atividade", max_length=60),
        ),
    ]
