# Generated by Django 4.2 on 2023-11-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grades", "0004_assessment_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessment",
            options={"ordering": ["day"]},
        ),
        migrations.AddField(
            model_name="assessment",
            name="weight",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
