# Generated by Django 4.2 on 2023-11-07 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0003_alter_programming_classroom_and_more"),
        ("grades", "0006_grade_justification"),
    ]

    operations = [
        migrations.AddField(
            model_name="mention",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentions",
                to="management.subject",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="value",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "I"), (1, "R"), (2, "B"), (3, "MB")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="mention",
            name="value",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "I"), (1, "R"), (2, "B"), (3, "MB")], default=2
            ),
        ),
    ]
