# Generated by Django 4.2 on 2023-11-10 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("grades", "0007_mention_subject_alter_grade_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
