# Generated by Django 4.2 on 2023-10-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(default="", max_length=60),
        ),
    ]
