# Generated by Django 4.2 on 2023-09-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=80)),
                ("date", models.DateField(auto_now=True)),
                ("image", models.ImageField(null=True, upload_to="communicate/covers")),
                ("private", models.BooleanField(default=False)),
                ("info", models.TextField()),
                ("place", models.CharField(max_length=63, null=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.classroom",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
