# Generated by Django 4.2 on 2023-10-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0002_alter_announcement_date_alter_announcement_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="category",
            field=models.CharField(default="*", max_length=15),
        ),
    ]
