# Generated by Django 4.2 on 2023-09-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0002_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="image",
            field=models.ImageField(null=True, upload_to="announcement/covers"),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(null=True, upload_to="event/covers"),
        ),
    ]
