# Generated by Django 4.2 on 2023-10-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0003_rename_tags_alert_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="date",
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
