# Generated by Django 4.2 on 2023-11-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0004_alter_alert_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(),
        ),
    ]
