# Generated by Django 4.2 on 2025-11-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0005_alter_event_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="announcements/"),
        ),
    ]
